"""
McLeuker Agentic AI Platform - Professional Word Document Generator

Creates professional, well-formatted Word documents with proper styling,
headers, footers, and structure like Manus AI.
"""

import os
from typing import Optional, List, Dict, Any
from datetime import datetime
from dataclasses import dataclass, field

from docx import Document
from docx.shared import Inches, Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from src.config.settings import get_settings


@dataclass
class WordSection:
    """A section in the Word document."""
    title: str
    content: str
    level: int = 1
    bullet_points: Optional[List[str]] = None
    table_data: Optional[List[List[str]]] = None


@dataclass
class GeneratedWordFile:
    """Result of Word document generation."""
    filename: str
    filepath: str
    size_bytes: int
    page_count: int
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "filename": self.filename,
            "filepath": self.filepath,
            "size_bytes": self.size_bytes,
            "page_count": self.page_count,
            "created_at": self.created_at.isoformat()
        }


class ProfessionalWordGenerator:
    """
    Professional Word document generator.
    
    Creates well-formatted Word documents with:
    - Professional styling and colors
    - Headers and footers
    - Tables and lists
    - Proper typography
    """
    
    # Professional color scheme
    COLORS = {
        "primary": RGBColor(31, 78, 121),      # Dark blue
        "secondary": RGBColor(46, 117, 182),   # Medium blue
        "accent": RGBColor(91, 155, 213),      # Light blue
        "text": RGBColor(51, 51, 51),          # Dark gray
    }
    
    def __init__(self, output_dir: Optional[str] = None):
        self.settings = get_settings()
        self.output_dir = output_dir or self.settings.OUTPUT_DIR
        os.makedirs(self.output_dir, exist_ok=True)
    
    async def generate(
        self,
        title: str,
        sections: List[WordSection],
        filename: Optional[str] = None,
        author: str = "McLeuker AI",
        subtitle: Optional[str] = None
    ) -> GeneratedWordFile:
        """
        Generate a professional Word document.
        
        Args:
            title: Document title
            sections: List of document sections
            filename: Optional filename
            author: Document author
            subtitle: Optional subtitle
            
        Returns:
            GeneratedWordFile with file details
        """
        doc = Document()
        
        # Set up document properties
        doc.core_properties.author = author
        doc.core_properties.title = title
        
        # Set up styles
        self._setup_styles(doc)
        
        # Add title
        title_para = doc.add_paragraph()
        title_run = title_para.add_run(title)
        title_run.font.size = Pt(24)
        title_run.font.bold = True
        title_run.font.color.rgb = self.COLORS["primary"]
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_para.space_after = Pt(6)
        
        # Add subtitle
        if subtitle:
            subtitle_para = doc.add_paragraph()
            subtitle_run = subtitle_para.add_run(subtitle)
            subtitle_run.font.size = Pt(14)
            subtitle_run.font.italic = True
            subtitle_run.font.color.rgb = self.COLORS["secondary"]
            subtitle_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add date and author
        date_str = datetime.utcnow().strftime("%B %d, %Y")
        meta_para = doc.add_paragraph()
        meta_run = meta_para.add_run(f"Generated by {author} on {date_str}")
        meta_run.font.size = Pt(10)
        meta_run.font.italic = True
        meta_run.font.color.rgb = self.COLORS["text"]
        meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        meta_para.space_after = Pt(20)
        
        # Add horizontal line
        self._add_horizontal_line(doc)
        
        # Add sections
        for section in sections:
            self._add_section(doc, section)
        
        # Generate filename
        if not filename:
            timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
            safe_title = "".join(c if c.isalnum() else "_" for c in title[:30])
            filename = f"{safe_title}_{timestamp}.docx"
        
        if not filename.endswith('.docx'):
            filename += '.docx'
        
        filepath = os.path.join(self.output_dir, filename)
        
        # Save document
        doc.save(filepath)
        
        # Get file info
        size_bytes = os.path.getsize(filepath)
        page_count = max(1, len(sections) // 3 + 1)
        
        return GeneratedWordFile(
            filename=filename,
            filepath=filepath,
            size_bytes=size_bytes,
            page_count=page_count
        )
    
    def _setup_styles(self, doc: Document):
        """Set up document styles."""
        # Modify Normal style
        style = doc.styles['Normal']
        style.font.name = 'Calibri'
        style.font.size = Pt(11)
        style.font.color.rgb = self.COLORS["text"]
        
        # Set up heading styles
        for i in range(1, 4):
            style_name = f'Heading {i}'
            if style_name in doc.styles:
                style = doc.styles[style_name]
                style.font.name = 'Calibri'
                style.font.bold = True
                
                if i == 1:
                    style.font.size = Pt(16)
                    style.font.color.rgb = self.COLORS["primary"]
                elif i == 2:
                    style.font.size = Pt(14)
                    style.font.color.rgb = self.COLORS["secondary"]
                else:
                    style.font.size = Pt(12)
                    style.font.color.rgb = self.COLORS["accent"]
    
    def _add_section(self, doc: Document, section: WordSection):
        """Add a section to the document."""
        # Add heading
        if section.level == 1:
            heading = doc.add_heading(section.title, level=1)
        elif section.level == 2:
            heading = doc.add_heading(section.title, level=2)
        else:
            heading = doc.add_heading(section.title, level=3)
        
        # Add content
        if section.content:
            paragraphs = section.content.split('\n\n')
            for para_text in paragraphs:
                if para_text.strip():
                    para = doc.add_paragraph()
                    run = para.add_run(para_text.strip())
                    run.font.size = Pt(11)
                    run.font.color.rgb = self.COLORS["text"]
                    para.paragraph_format.space_after = Pt(8)
                    para.paragraph_format.line_spacing_rule = WD_LINE_SPACING.MULTIPLE
                    para.paragraph_format.line_spacing = 1.15
        
        # Add bullet points
        if section.bullet_points:
            for point in section.bullet_points:
                para = doc.add_paragraph(point, style='List Bullet')
                para.paragraph_format.space_after = Pt(4)
        
        # Add table
        if section.table_data and len(section.table_data) > 0:
            self._add_table(doc, section.table_data)
        
        # Add spacing after section
        doc.add_paragraph()
    
    def _add_table(self, doc: Document, data: List[List[str]]):
        """Add a styled table to the document."""
        if not data or len(data) == 0:
            return
        
        rows = len(data)
        cols = len(data[0]) if data[0] else 1
        
        table = doc.add_table(rows=rows, cols=cols)
        table.style = 'Table Grid'
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        
        # Fill in data
        for i, row_data in enumerate(data):
            row = table.rows[i]
            for j, cell_text in enumerate(row_data):
                cell = row.cells[j]
                cell.text = str(cell_text) if cell_text else ""
                
                # Style header row
                if i == 0:
                    cell.paragraphs[0].runs[0].font.bold = True
                    cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(255, 255, 255)
                    
                    # Set background color
                    shading = OxmlElement('w:shd')
                    shading.set(qn('w:fill'), '1F4E79')
                    cell._tc.get_or_add_tcPr().append(shading)
                
                cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add spacing after table
        doc.add_paragraph()
    
    def _add_horizontal_line(self, doc: Document):
        """Add a horizontal line to the document."""
        para = doc.add_paragraph()
        para.paragraph_format.space_before = Pt(10)
        para.paragraph_format.space_after = Pt(10)
        
        # Create a border element
        pBdr = OxmlElement('w:pBdr')
        bottom = OxmlElement('w:bottom')
        bottom.set(qn('w:val'), 'single')
        bottom.set(qn('w:sz'), '6')
        bottom.set(qn('w:space'), '1')
        bottom.set(qn('w:color'), 'CCCCCC')
        pBdr.append(bottom)
        para._p.get_or_add_pPr().append(pBdr)
    
    async def generate_from_text(
        self,
        title: str,
        content: str,
        filename: Optional[str] = None
    ) -> GeneratedWordFile:
        """
        Generate Word document from plain text content.
        
        Args:
            title: Document title
            content: Text content
            filename: Optional filename
            
        Returns:
            GeneratedWordFile
        """
        # Parse content into sections
        sections = []
        parts = content.split('\n\n')
        
        current_section = None
        for part in parts:
            part = part.strip()
            if not part:
                continue
            
            if part.startswith('# '):
                if current_section:
                    sections.append(current_section)
                current_section = WordSection(
                    title=part[2:].strip(),
                    content="",
                    level=1
                )
            elif part.startswith('## '):
                if current_section:
                    sections.append(current_section)
                current_section = WordSection(
                    title=part[3:].strip(),
                    content="",
                    level=2
                )
            elif part.startswith('- ') or part.startswith('* '):
                if current_section:
                    if current_section.bullet_points is None:
                        current_section.bullet_points = []
                    current_section.bullet_points.append(part[2:].strip())
            else:
                if current_section:
                    if current_section.content:
                        current_section.content += "\n\n" + part
                    else:
                        current_section.content = part
                else:
                    current_section = WordSection(
                        title="Overview",
                        content=part,
                        level=1
                    )
        
        if current_section:
            sections.append(current_section)
        
        if not sections:
            sections = [WordSection(
                title="Content",
                content=content,
                level=1
            )]
        
        return await self.generate(title, sections, filename)
    
    async def generate_report(
        self,
        title: str,
        summary: str,
        findings: List[Dict[str, Any]],
        conclusion: str,
        filename: Optional[str] = None
    ) -> GeneratedWordFile:
        """
        Generate a structured report Word document.
        
        Args:
            title: Report title
            summary: Executive summary
            findings: List of findings
            conclusion: Conclusion text
            filename: Optional filename
            
        Returns:
            GeneratedWordFile
        """
        sections = [
            WordSection(
                title="Executive Summary",
                content=summary,
                level=1
            )
        ]
        
        for i, finding in enumerate(findings, 1):
            sections.append(WordSection(
                title=finding.get("title", f"Finding {i}"),
                content=finding.get("content", ""),
                level=2,
                bullet_points=finding.get("points"),
                table_data=finding.get("table")
            ))
        
        sections.append(WordSection(
            title="Conclusion",
            content=conclusion,
            level=1
        ))
        
        return await self.generate(title, sections, filename)


# Global generator instance
_word_generator: Optional[ProfessionalWordGenerator] = None


def get_word_generator(output_dir: Optional[str] = None) -> ProfessionalWordGenerator:
    """Get or create the global Word generator."""
    global _word_generator
    if _word_generator is None:
        _word_generator = ProfessionalWordGenerator(output_dir)
    return _word_generator
